version: "3.3"

services:
    # consul:
    #     #镜像：镜像名称:版本号
    #     image: consul:latest
    #     #主机名
    #     hostname: "registry"
    #     #暴露端口
    #     ports:
    #         - "8300:8300"
    #         - "8400:8400"
    #         - "8500:8500"
    #         - "8600:53/udp"
    #     container_name: consul

    # node_server:
    #     image: node:16-alpine
    #     container_name: node_server
    #     ports:
    #         - 8000:8000
    #     volumes:
    #         - ./nodeServer/src:/app
    #     working_dir: /app
    #     command: npm run dev
    #     depends_on:
    #         - consul
    #     links:
    #         - consul

    go_server:
        image: alpine
        container_name: go_server
        build:
            context: ./goServer
            dockerfile: Dockerfile
            target: app
        # command: app
        # ports:
        #     - 8080:8080
        # depends_on:
        #     - consul
        # links:
        #     - consul

    # web:
    #     build:
    #       context: ./web
    #       dockerfile: Dockerfile
    #       target: app
    #     ports:
    #       - 8000:8000
    #     links:
    #       - consul
