serverversion: 2.3.0
#---------------Infrastructure configuration---------------------#
# etcd:
#   etcdSchema: openim  #默认即可
#   etcdAddr: [ 127.0.0.1:2379 ] #单机部署时，默认即可

# k8sMod: false #开启k8s模式 使用pod里面环境变量请求services调用服务 而并非etcd

mysql:
  dbMysqlAddress: [ 127.0.0.1:13306 ] #mysql地址 目前仅支持单机，默认即可
  dbMysqlUserName: root #mysql用户名，建议修改
  dbMysqlPassword: knightxv # mysql密码，建议修改
  dbMysqlDatabaseName: knightxv #默认即可
  dbTableName: eMsg #默认即可
  dbMsgTableNum: 1
  dbMaxOpenConns: 20
  dbMaxIdleConns: 10
  dbMaxLifeTime: 120

mongo:
  dbUri: ""#当dbUri值不为空则直接使用该值
  dbAddress: 127.0.0.1:37017  #单机时为mongo地址，使用分片集群时，为mongos地址 默认即可
  dbDirect: false
  dbTimeout: 60
  dbDatabase: knightxv  #mongo db 默认即可
  dbSource: admin
  dbUserName:  #mongo用户名，建议先不设置
  dbPassword:  #mongo密码，建议先不设置
  dbMaxPoolSize: 100
  dbRetainChatRecords: 3650 #mongo保存离线消息时间（天），根据需求修改

redis:
  dbAddress: [ 127.0.0.1:16379 ] #redis地址 单机时，填写一个地址即可，使用redis集群时候，填写集群中多个节点地址（主从地址都可以填写，增加容灾能力），默认即可
  dbMaxIdle: 128
  dbMaxActive: 0
  dbIdleTimeout: 120
  dbUserName:     #only redis version 6.0+ need username
  dbPassWord: knightxv #redis密码 建议修改
  enableCluster: false #如果外部redis以集群方式启动，需要打开此开关

kafka:
  ws2mschat:
    addr: [ 127.0.0.1:9092 ] #kafka配置，默认即可
    topic: "ws2ms_chat" #用于mongo和mysql保存消息
  ws2mschatoffline:
    addr: [ 127.0.0.1:9092 ] #kafka配置，默认即可
    topic: "ws2ms_chat_offline" #原为离线用户消息处理，目前暂时弃用
  msgtomongo:
    addr: [ 127.0.0.1:9092 ] #kafka配置，默认即可
    topic: "msg_to_mongo"
  ms2pschat:
    addr: [ 127.0.0.1:9092 ] #kafka配置，默认即可
    topic: "ms2ps_chat" #消息push
  consumergroupid:
    msgToTransfer: mongo
    msgToMongo: mongo_ex
    msgToMySql: mysql
    msgToPush: push

#token config
tokenpolicy:
  accessSecret: "open_im_server" #token生成相关，默认即可
  # Token effective time day as a unit
  accessExpire: 3650 #token过期时间（天） 默认即可
messageverify:
  friendVerify: false